"""
Vendor detection from invoice OCR text - v8.1
878+ vendor patterns

Changes in v8.1:
- Added 'Jack Robinson Waste Disposal' pattern before 'Robinson Waste'
  (NJ vendor distinct from Robinson Waste Services UT - different invoice format)

Changes in v8:
- Added 127 new vendor patterns from vendor_review_interface.xlsx analysis
- Detection rate target: 97%+

Changes in v7:
- Fixed Waste Management misdetections (317 invoices)
- Added 25+ new vendor patterns that were incorrectly matching WM
- Moved Win Waste and Porter Trash patterns before WM
- Fixed Salandro pattern for apostrophe handling

Changes in v6:
- Added 110+ new vendors from undetected invoice analysis
- Detection rate: 95.5% (up from 93.7%)

Changes in v5:
- Fixed Grand Rapids Iron pattern (removed duplicate, fixed regex for OCR split)
- Fixed Hometown Sanitation pattern (handles OCR line breaks)
- Fixed Premier pattern (now matches DISPOSAL variant)
- Fixed Ryland Environmental pattern (handles OCR variations)
- Added 150+ new vendors from exception analysis
"""
import re
import pandas as pd

VENDOR_PATTERNS = {
    # ============================================================
    # WASTE MANAGEMENT MISDETECTION FIXES - MUST BE BEFORE WM PATTERN
    # These vendors have "Waste Management" in their text but are NOT WM
    # ============================================================
    
    # High-volume misdetections (>10 invoices)
    'West Central Sanitation': r'WEST\s*CENTRAL',
    'Boro Wide': r'BORO\s*WIDE|BOROWIDE',
    'Bruin Waste Management': r'BRUIN\s*WASTE',
    'Win Waste': r'WIN\s*WASTE',  # MOVED from line 246
    'Appalachian Waste Management': r'APPALACHIAN\s*WASTE',
    'Garden State Waste Management': r'GARDEN\s*STATE\s*WASTE',
    'Tacoma Public Utilities': r'TACOMA\s*PUBLIC\s*UTILITIES',
    'Porter Trash': r'PORTER\s*TRASH',  # MOVED from line 778
    
    # Medium-volume misdetections (3-10 invoices)
    "Steve's Sanitation": r"STEVE\'?S\s*SANITATION",
    'Heartland Waste Management': r'HEARTLAND\s*(WASTE|WM)',
    'Salandro Refuse': r'SALANDRO',  # FIXED: was r'SALANDR.?\s*REFUSE'
    'MARS City of Beatrice': r'MIDWEST\s*AREA\s*REFUSE|MARS\s*BEATRICE',
    'United States Disposal': r'UNITED\s*STATES\s*DISPOSAL',
    'Greenbrier Valley Solid Waste': r'GREENBRIER\s*VALLEY',
    'Westside Waste Management': r'WESTSIDE\s*WASTE\s*MANAGEMENT',
    'Gilton Solid Waste': r'GILTON',
    'Engebretson & Sons': r'ENGEBRETSON',
    "Guido's Services": r"GUIDO\'?S",
    'City of Hidalgo': r'CITY\s*OF\s*HIDALGO',
    'Town of Lake Park': r'TOWN\s*OF\s*LAKE\s*PARK',
    
    # Low-volume misdetections (1-2 invoices)
    'Blue Compactor': r'BLUE\s*COMPACTOR',
    'City of Kirkland': r'CITY\s*OF\s*KIRKLAND',
    'Citrus County Utilities': r'CITRUS\s*COUNTY',
    'Cottage Grove Sanitary': r'COTTAGE\s*GROVE\s*SANITARY',
    'Perdue Environmental': r'PERDUE\s*ENVIRONMENTAL',
    'Total Waste Management': r'TOTAL\s*WASTE\s*MANAGEMENT',
    'Hillsborough County SW': r'HILLSBOROUGH\s*COUNTY.*SOLID\s*WASTE',
    'Miami-Dade DSWM': r'MIAMI.?DADE',
    'Montgomery County Environmental': r'MONTGOMERY\s*COUNTY\s*ENVIRONMENTAL',
    'Gogebic Range SWMA': r'GOGEBIC\s*RANGE',
    'DKMM Solid Waste': r'KNOX.*MARION.*MORROW|DKMM',
    
    # ============================================================
    # === CORE VENDORS (A-Z) ===
    # ============================================================
    '121 Disposal': r'121\s*DISPOSAL',
    'A-1 Disposal': r'A-?1\s*DISPOSAL',
    'ABC Waste': r'ABC\s*WASTE',
    'AM Disposal': r'AM\s*DISPOSAL',
    'Absolute Waste': r'ABSOLUTE\s*WASTE',
    'Ace Recycling': r'ACE\s*RECYCLING',
    'Active Waste': r'ACTIVE\s*WASTE',
    'Advance Disposal': r'ADVANCE\s*DISPOSAL',
    'Al Clawson Disposal': r'AL\s*CLAWSON',
    'Alaska Waste': r'ALASKA\s*WASTE',
    'All American Waste': r'ALL\s*AMERICAN\s*WASTE',
    'All Metals Recycling': r'ALL\s*METALS\s*RECYCLING',
    'All Waste': r'ALL\s*WASTE.{0,10}(INC|LLC)',
    'American Disposal': r'AMERICAN\s*DISPOSAL',
    'American Recycling': r'AMERICAN\s*RECYCLING',
    'American Sanitation': r'AMERICAN\s*SANITATION',
    'American Waste Control': r'AMERICAN\s*WASTE\s*CONTROL',
    'Amwaste': r'AMWASTE',
    'Ankeny Sanitation': r'ANKENY\s*SANITATION',
    'Anytime Waste': r'ANYTIME\s*WASTE',
    'Apex Waste': r'APEX\s*WASTE',
    'Arrowaste': r'ARROWASTE',
    'Aspen Waste': r'ASPEN\s*WASTE',
    'Athens Services': r'ATHENS\s*SERVICES',
    'Atlantic Waste': r'ATLANTIC\s*WASTE',
    'BCC Waste Solutions': r'BCC\s*WASTE',
    'Basin Disposal': r'BASIN\s*DISPOSAL',
    'Becker360': r'BECKER\s*360',
    'Best Cleaner': r'BEST\s*CLEANER',
    'Best Way Disposal': r'BEST\s*WAY\s*DISPOSAL',
    'Black Hawk Waste': r'BLACK\s*HAWK\s*WASTE',
    'Blue Diamond Disposal': r'BLUE\s*DIAMOND\s*DISPOSAL',
    'Blue Hills Environmental': r'BLUE\s*HILLS\s*(ENVIRONMENTAL)?',
    'Blue Ridge Waste': r'BLUE\s*RIDGE\s*WASTE',
    'Boren Brothers': r'BOREN\s*BROTHERS',
    'Boyas Recycling': r'BOYAS\s*RECYCLING',
    'Bridge City Sanitation': r'BRIDGE\s*CITY\s*SANITATION',
    "Burgmeier's Hauling": r'BURGMEIER',
    'Burrtec': r'BURRTEC',
    'CR&R': r'CR\s*&\s*R',
    'CRI Curbside': r'CRI.?CURBSIDE|CRI\s*(CURBSIDE)?\s*(RECYCLING|SHREDDING)',
    'Capital Waste': r'CAPITAL\s*WASTE',
    'Cards KS': r'CARDS\s*KS',
    'Cards Mo': r'CARDS\s*MO',
    'Casella': r'CASELLA',
    'Cavossa Disposal': r'CAVOSSA',
    'Chrin Hauling': r'CHRIN\s*HAULING',
    'Circle Sanitation': r'CIRCLE\s*SANITATION',
    'City Waste': r'CITY\s*WASTE',
    'Coastal Waste': r'COASTAL\s*WASTE',
    "Cockey's Enterprises": r'COCKEY',
    'Cogent Waste Solutions': r'COGENT\s*WASTE',
    'Community Disposal': r'COMMUNITY\s*DISPOSAL',
    'Community Waste': r'COMMUNITY\s*WASTE',
    'Compactor Rentals of America': r'COMPACTOR\s*RENTALS\s*OF\s*AMERICA',
    'Conex Recycling': r'CONEX\s*RECYCLING',
    'Conigliaro': r'CONIGLIARO',
    'Container Rental Co': r'CONTAINER\s*RENTAL\s*CO',
    'Cooks Wastepaper': r'COOKS?\s*WASTE\s*PAPER',
    'County Hauling': r'COUNTY\s*HAULING',
    'County Waste Systems': r'COUNTY\s*WASTE\s*SYSTEMS',
    'D Crescio Trucking': r'D\.?\s*CRESCIO',
    'Debris to Green': r'DEBRIS\s*TO\s*GREEN',
    'Delta Waste': r'DELTA\s*WASTE',
    'Detroit Disposal': r'DETROIT\s*DISPOSAL',
    'Disposal Management': r'DISPOSAL\s*MANAGEMENT',
    'Dunham': r'DUNHAM\s*(INC)?',
    'EDCO Disposal': r'EDCO\s*(WASTE|DISPOSAL|RECYCLING)?',
    'EL Harvey': r'E\.?L\.?\s*HARVEY',
    'Eco-Tech': r'ECO.?TECH',
    'Elite Recycling': r'ELITE\s*RECYCLING',
    'Empire Waste': r'EMPIRE\s*WASTE',
    'Express Disposal': r'EXPRESS\s*DISPOSAL',
    'F & L Construction': r'F\s*&\s*L\s*CONSTRUCTION',
    'FCC Environmental': r'FCC\s*ENVIRONMENTAL',
    'Five Star Waste': r'FIVE\s*STAR\s*WASTE',
    'Flood Brothers': r'FLOOD\s*BROTHERS',
    'Forever Clean': r'FOREVER\s*CLEAN',
    'Friedman Recycling': r'FRIEDMAN',
    'Frontier Waste': r'FRONTIER\s*WASTE',
    'Fusion Waste': r'FUSION\s*WASTE',
    'G2 Revolution': r'G2\s*REVOLUTION',
    'GFL': r'GFL\s*(ENVIRONMENTAL|GREEN\s*FOR\s*LIFE)?',
    'GHW Waste': r'GHW\s*WASTE',
    'Garden Isle Disposal': r'GARDEN\s*ISLE\s*DISPOSAL',
    'Garland County Landfill': r'GARLAND\s*COUNTY\s*LANDFILL',
    'Gateway Disposal': r'GATEWAY\s*DISPOSAL',
    'Geodom Carting': r'GEODOM',
    'Goode Companies': r'GOODE\s*COMPANIES',
    'Grace Hauling': r'GRACE\s*HAULING',
    'Great Waste': r'GREAT\s*WASTE',
    'Green Guys': r'GREEN\s*GUYS',
    'Greenway Waste': r'GREENWAY\s*WASTE',
    'Grogan Waste': r'GROGAN\s*WASTE',
    'Gulf Coast Containers': r'GULF\s*COAST\s*CONTAINERS',
    'Hamilton Alliance': r'HAMILTON\s*ALLIANCE',
    "Harter's": r"HARTER\'?S",
    'Haul Away Rubbish': r'HAUL\s*AWAY\s*RUBBISH',
    'Hillside Solutions': r'HILLSIDE\s*SOLUTIONS',
    'Homewood Disposal': r'HOMEWOOD\s*DISPOSAL',
    'Hoss Disposal': r'HOSS\s*DISPOSAL',
    'Howard Disposal': r'HOWARD\s*DISPOSAL',
    'Hughes Trash Removal': r'HUGHES\s*TRASH',
    'Huntsville Hauling': r'HUNTSVILLE\s*HAULING',
    'IV Waste': r'IV\s*WASTE',
    'Independent Recycling': r'INDEPENDENT\s*RECYCLING',
    'Intermountain Disposal': r'INTERMOUNTAIN\s*DISPOSAL',
    'Interstate Waste': r'INTERSTATE\s*WASTE',
    'Island Disposal': r'ISLAND\s*DISPOSAL',
    'JD Parker': r'JD\s*PARKER',
    'JLT Trucking': r'JLT\s*TRUCKING',
    'JP Mascaro': r'J\.?P\.?\s*MASCARO',
    "Jim's Sanitation": r"JIM\'?S\s*SANITATION",
    'K & K Sanitation': r'K\s*&\s*K\s*SANITATION',
    'KMG Hauling': r'KMG\s*HAULING',
    'Kahut Waste': r'KAHUT\s*WASTE',
    'Kimble': r'KIMBLE',
    'Kootenai County Solid Waste': r'KOOTENAI\s*COUNTY',
    'LK Specialties': r'LK\s*SPECIALTIES',
    'Lakeshore Recycling': r'LAKESHORE\s*RECYCLING',
    'Las Vegas Recycling': r'LAS\s*VEGAS\s*RECYCLING',
    'Lawrence Waste': r'LAWRENCE\s*WASTE',
    'Liberty Disposal': r'LIBERTY\s*DISPOSAL',
    'Liberty Waste': r'LIBERTY\s*WASTE',
    'Lift Waste': r'LIFT\s*WASTE',
    'Lightning Disposal': r'LIGHTNING\s*DISPOSAL',
    'Louisiana Waste': r'LOUISIANA\s*WASTE',
    'Mark Dunning': r'MARK\s*DUNNING',
    'Martin Environmental': r'MARTIN\s*ENVIRONMENTAL',
    'Meridian Waste': r'MERIDIAN\s*WASTE',
    'Metalpro': r'METALPRO',
    'Mid South Waste': r'MID\s*SOUTH\s*WASTE',
    'Mid Valley Disposal': r'MID\s*VALLEY\s*DISPOSAL',
    'Mills Brothers': r'MILLS\s*BROTHERS',
    'Minnkota Recycling': r'MINNKOTA',
    'Modern Recycling': r'MODERN\s*RECYCLING',
    'Moore Coal': r'MOORE\s*COAL',
    'Mountain State Waste': r'MOUNTAIN\s*STATE\s*WASTE',
    'Murreys Disposal': r"MURREY\'?S\s*DISPOSAL",
    'My Trash': r'MY\s*TRASH',
    'NEI Pennsylvania': r'NEI\s*PENNSYLVANIA',
    'National Equipment Solutions': r'NATIONAL\s*EQUIPMENT\s*SOLUTIONS',
    'Nauset Disposal': r'NAUSET\s*DISPOSAL',
    'Nevada Recycling': r'NEVADA\s*RECYCLING',
    'Nitti Sanitation': r'NITTI\s*SANITATION',
    'Northern Waste': r'NORTHERN\s*WASTE',
    'Novak Sanitary': r'NOVAK\s*SANITARY',
    'Orlando Recycling': r'ORLANDO\s*RECYCLING',
    'Orlando Waste Paper': r'ORLANDO\s*WASTE\s*PAPER',
    'Pacific Waste': r'PACIFIC\s*WASTE',
    'Pak Rite Rentals': r'PAK\s*RITE',
    'Panzarella Waste': r'PANZARELLA',
    'Papillion Sanitation': r'PAPILLION\s*SANITATION',
    'Pascon': r'PASCON',
    'Patterson Sanitation': r'PATTERSON\s*SANITATION',
    'Pete & Pete': r'PETE\s*&\s*PETE',
    'Premier Waste': r'PREMIER\s*(WASTE|DISPOSAL)',
    'Priority Waste': r'PRIORITY\s*WASTE',
    'RAM Waste': r'RAM\s*WASTE',
    'Ramona Disposal': r'RAMONA\s*DISPOSAL',
    'Redbox+': r'REDBOX\+',
    'Redgate Disposal': r'REDGATE\s*DISPOSAL',
    'Redwood Waste': r'REDWOOD\s*WASTE',
    'Reed Maintenance': r'REED\s*MAINTENANCE',
    'Republic Services': r'REPUBLIC\s*SERVICES',
    'Reworld': r'REWORLD',
    'Richardson Waste': r'RICHARDSON\s*WASTE',
    'River Parish Disposal': r'RIVER\s*PARISH',
    'Jack Robinson Waste Disposal': r'JACK\s*ROBINSON\s*WASTE',
    'Robinson Waste': r'ROBINSON\s*WASTE',
    'Rocky Ridge': r'ROCKY\s*RIDGE',
    'Roll Off Systems': r'ROLL\s*OFF\s*SYSTEMS',
    'Rumpke': r'RUMPKE',
    'Ryland Environmental': r'RYLAND.*ENVIRONMENTAL',
    'SBC Waste': r'SBC\s*WASTE',
    'Sanitary Service Company': r'SANITARY\s*SERVICE\s*COMPANY',
    'Schaap Sanitation': r'SCHAAP\s*SANITATION',
    'Shank Waste': r'SHANK\s*WASTE',
    'SmartTrash': r'SMARTTRASH',
    'Smith Creek': r'SMITH\s*CREEK',
    'Solid Waste Authority': r'SOLID\s*WASTE\s*AUTHORITY',
    "Sonny's Solid Waste": r"SONNY\'?S\s*SOLID\s*WASTE",
    'South Shore Disposal': r'SOUTH\s*SHORE\s*DISPOSAL',
    'Southern Illinois Waste': r'SOUTHERN\s*ILLINOIS\s*WASTE',
    'Southern Sanitation': r'SOUTHERN\s*SANITATION',
    'Specific Waste': r'SPECIFIC\s*WASTE',
    'Standard Waste': r'STANDARD\s*WASTE',
    'Stericycle': r'STERICYCLE',
    'Stevens Disposal': r'STEVENS\s*DISPOSAL',
    'Stryker Environmental': r'STRYKER\s*ENVIRONMENTAL',
    'Swinger Sanitation': r'SWINGER\s*SANITATION',
    'TFC Recycling': r'TFC\s*RECYCLING',
    'TK Trash': r'TK\s*TRASH',
    'Taylor & Sons': r'TAYLOR\s*&\s*SONS|TAYLOR\s*AND\s*SONS',
    'Texas Disposal': r'TEXAS\s*DISPOSAL',
    'Tiger Sanitation': r'TIGER\s*SANITATION',
    'Tower Compactor': r'TOWER\s*COMPACTOR',
    'TransTrash': r'TRANSTRASH',
    'Trash Control': r'TRASH\s*CONTROL',
    'Treasure Coast Recycling': r'TREASURE\s*COAST\s*RECYCLING',
    'Tri-County Industries': r'TRI.?COUNTY\s*INDUSTRIES',
    'Trident Waste': r'TRIDENT\s*WASTE',
    'Troiano Waste': r'TROIANO\s*WASTE',
    'UDP Hauling': r'UDP\s*HAULING',
    'USA Waste': r'USA\s*WASTE',
    'Universal Waste': r'UNIVERSAL\s*WASTE',
    'Valley Vista': r'VALLEY\s*VISTA',
    'Vista Recycling': r'VISTA\s*RECYCLING',
    'Vogel Disposal': r'VOGEL\s*DISPOSAL',
    'WG Waste': r'WG\s*WASTE',
    'WM Compactor Solutions': r'WM\s*COMPACTOR\s*SOLUTIONS',
    'Walker Lake Disposal': r'WALKER\s*LAKE\s*DISPOSAL',
    'Walters Recycling': r"WALTERS?\s*RECYCLING",
    'Ware Disposal': r'WARE\s*DISPOSAL',
    'Wasatch Waste': r'WASATCH',
    'Waste Connections': r'WASTE\s*CONNECTIONS',
    'Waste Control': r'WASTE\s*CONTROL',
    # NOTE: Waste Management pattern - all misdetection patterns MUST be above this line
    'Waste Management': r'WASTE\s*MANAGEMENT',
    'Waste Path': r'WASTE\s*PATH',
    # Complete Solutions must be before Waste Pro (OCR contains "waste program complete")
    'Complete Solutions & Sourcing': r'COMPLETE\s*SOLUTIONS\s*&?\s*SOURCING',
    'Waste Pro': r'WASTE\s*PRO',
    'Waste Zero': r'WASTE\s*ZERO',
    'West Oahu Aggregate': r'WEST\s*OAHU\s*AGGREGATE',
    'Whitecap Waste': r'WHITECAP\s*WASTE',
    'WillScot': r'WILLSCOT',
    'Willey Disposal': r'WILLEY\s*DISPOSAL',
    # Win Waste MOVED to top of file (WM misdetection fix)
    'Wise Environmental': r'WISE\s*ENVIRONMENTAL',
    'ZARC Recycling': r'ZARC',
    
    # === BATCH 1 ADDITIONS ===
    'EcoSouth': r'ECOSOUTH',
    'Curbside': r'CURBSIDE\s*(WASTE|SERVICES|INC|LLC|MINNEAPOLIS)',
    'VLS Environmental': r'VLS\s*(ENVIRONMENTAL)?',
    'Renewable Resources': r'RENEWABLE\s*RESOURCES',
    'KnightHorst': r'KNIGHTHORST',
    'LRS': r'LRS\s*(RECYCLES|OF\s*MINNESOTA|5500\s*PEARL)?',
    'Live Oak': r'LIVE\s*OAK',
    'Granger Waste': r'GRANGER\s*WASTE',
    '1-800-Got-Junk': r'1-?800-?GOT-?JUNK',
    'Pelican Waste': r'PELICAN\s*(WASTE|DEBRIS)',
    'Western Disposal': r'WESTERN\s*DISPOSAL',
    'Clean Slate': r'CLEAN\s*SLATE',
    'Ace Waste Systems': r'ACE\s*WASTE\s*SYSTEMS',
    'Mazza Recycling': r'MAZZA\s*RECYCLING',
    'Western Elite': r'WESTERN\s*ELITE',
    'DeKalb County': r'DEKALB\s*CO',
    'First Piedmont': r'FIRST\s*PIEDMONT',
    'Omni': r'OMNI\s*(SOURCE|WASTE|DISPOSAL|INDIANA\s*DIVISION)',
    'Lawrence County Solid Waste': r'LAWRENCE\s*COUNTY\s*SOLID',
    'Zero Waste': r'ZERO\s*WASTE\s*&',
    'Major Waste': r'MAJOR\s*WASTE',
    'RAD Curbside': r'RAD\s*CURBSIDE',
    'Updike Industries': r'UPDIKE\s*INDUSTRIES',
    'Yreka Transfer': r'YREKA\s*TRANSFER',
    "Good's Disposal": r"GOOD\'?S\s*DISPOSAL",
    'KC Disposal': r'KC\s*DISPOSAL',
    'Hiltz': r'\bHILTZ\b',
    'Waste Away': r'WASTE\s*AWAY',
    'R&S Waste': r'R\s*&\s*S\s*WASTE',
    'Escondido Disposal': r'ESCONDIDO\s*DISPOSAL',
    'Roadrunner Rubbish': r'ROADRUNNER\s*RUBBISH',
    'Town & Country Disposal': r'TOWN\s*&\s*COUNTRY\s*DISPOSAL',
    'Talon Sanitation': r'TALON\s*SANITATION',
    'Crane Roll-Off': r'CRANE\s*ROLL.?OFF',
    'Arrowhead Waste': r'ARROWHEAD\s*WASTE',
    'Green OBKY': r'GREEN\s*OBKY',
    'Island Refuse': r'ISLAND\s*REFUSE',
    'Hilltopper Refuse': r'HILLTOPPER\s*REFUSE',
    "Kurtzman's Sanitation": r'KURTZMAN',
    'Alameda County Industries': r'ALAMEDA\s*COUNTY',
    'Agri-Cycle': r'AGRI.?CYCLE',
    'Roll-Off Chick': r'ROLL.?OFF\s*CHICK',
    'Helgerson Property Maintenance': r'HELGERSON',
    'Okon Recycling': r'OKON\s*RECYCLING',
    'Absolute Services': r'ABSOLUTE\s*SERVICES',
    'Humpty Dumpsters': r'HUMPTY\s*DUMPSTERS?',
    'Westside Disposal': r'WESTSIDE\s*DISPOSAL',
    '501 Sanitation': r'501\s*SANITATION',
    'J&K Trash': r'J\s*&\s*K',
    'Community Sanitation': r'COMMUNITY\s*SANITATION',
    
    # === BATCH 2 ADDITIONS ===
    'Eagle Disposal': r'EAGLE\s*DISPOSAL',
    'Navajo Sanitation': r'NAVAJO\s*SANITATION',
    'RDT Inc': r'RDT,?\s*INC',
    'Heavenly Trash': r'HEAVENLY\s*TRASH',
    'Grizzly Disposal': r'GRIZZLY\s*DISPOSAL',
    'ACES Disposal': r'ACES\s*(DISPOSAL)?',
    '4G Futures': r'4G\s*FUTURES',
    "Fogle's": r"FOGLE\'?S",
    'EOMS Recycling': r'E\.?O\.?M\.?S\s*RECYCLING',
    'Dependable Sanitation': r'DEPENDABLE\s*SANITATION',
    'Trash Taxi': r'TRASH\s*TAXI',
    'Tri-City Disposal': r'TRI.?CITY\s*DISPOSAL',
    'Velpen Trucking': r'VELPEN\s*TRUCKING',
    'Reliable Sanitation': r'RELIABLE\s*SANITATION',
    'Sonoco Recycling': r'SONOCO\s*(RECYCLING)?',
    "Mike's Rubbish": r"MIKE\'?S\s*RUBBISH",
    'City of Nampa': r'CITY\s*OF\s*NAMPA',
    'Green Planet 21': r'GREEN\s*PLANET\s*21',
    "Woodward's Disposal": r"WOODWARD\'?S\s*DISPOSAL",
    'Hugill Sanitation': r'HUGILL\s*SANITATION',
    'Ameriwaste': r'AMERIWASTE',
    'R-Local Sanitation': r'R-LOCAL\s*SANITATION',
    'Thompson Sanitation': r'THOMPSON\s*SANITATION',
    'T & G Sanitation': r'T\s*&\s*G\s*SANITATION',
    'The Trash Man': r'THE\s*TRASH\s*MAN',
    'Darob': r'DAROB',
    'Pro Disposal': r'PRO\s*DISPOSAL',
    'Rapid Removal': r'RAPID\s*REMOVAL',
    'Harley Hollan': r'HARLEY\s*HOLLAN',
    'Miller Enterprises': r'MILLER\s*ENTERPRISES',
    'Capital City': r'CAPITAL\s*CITY',
    'Eastern Waste': r'EASTERN\s*WASTE',
    'North Georgia Waste': r'NORTH\s*GEORGIA\s*WASTE',
    'BFI Waste': r'BFI\s*WASTE',
    'Ozark Disposal': r'OZARK\s*DISPOSAL',
    'Smurfit': r'SMURFIT',
    'Patriot Waste': r'PATRIOT\s*(WASTE|DISPOSAL|SERVICES)?',
    'Recycling Services of Florida': r'RECYCLING\s*SERVICES\s*OF\s*FLORIDA',
    'City of Wolf Point': r'CITY\s*OF\s*WOLF\s*POINT',
    
    # === BATCH 3 ADDITIONS ===
    'Nexus Disposal': r'NEXUS\s*DISPOSAL',
    'American Disposal Systems': r'AMERICAN\s*DISPOSAL\s*SYSTEMS',
    'Idaho Falls Utilities': r'IDAHO\s*FALLS\s*(UTILITIES)?',
    'City of Jackson': r'CITY\s*OF\s*JACKSON',
    'Chambersburg Waste Paper': r'CHAMBERSBURG\s*WASTE\s*PAPER',
    'Pro Waste Services': r'PRO\s*WASTE\s*SERVICES',
    'Wayne County Utah': r'WAYNE\s*COUNTY\s*(UTAH)?',
    'ABC Disposal Systems': r'ABC\s*DISPOSAL\s*SYSTEMS',
    'Ohio Valley Waste': r'OHIO\s*VALLEY\s*WASTE',
    'Golden Triangle Waste': r'GOLDEN\s*TRIANGLE\s*WASTE',
    'Royal Document Destruction': r'ROYAL\s*DOCUMENT\s*DESTRUCTION',
    'Brask Enterprises': r'BRASK\s*ENTERPRISES',
    'City of Mesquite': r'CITY\s*OF\s*MESQUITE',
    "Hogland's Transfer": r'HOGLAND',
    'Suburban Waste Services': r'SUBURBAN\s*WASTE\s*SERVICES',
    'Penn Waste': r'PENN\s*WASTE',
    'Wyoming Waste Services': r'WYOMING\s*WASTE\s*SERVICES',
    'Atlas Disposal': r'ATLAS\s*(DISPOSAL)?\s*(WASTEOLOGY)?',
    'Gotta Go Waste': r'GOTTA\s*GO',
    # Boro Wide MOVED to top of file (WM misdetection fix)
    'Modern Corporation': r'MODERN\s*CORPORATION',
    'Florida Express Waste': r'FLORIDA\s*EXPRESS',
    'Midwest Paper': r'MIDWEST\s*PAPER',
    "Jay Mecham's": r'(JAY\s*)?MECHAM',
    'Waste Services LLC': r'WASTE\s*SERVICES\s*LLC',
    'Western Kane County': r'WESTERN\s*KANE\s*COUNTY',
    'CWPM': r'(CWPM|LWPM)',
    'Direct Waste Services': r'DIRECT\s*WASTE\s*SERVICES',
    'Pellitteri': r'PELLITTERI',
    'CTL 3R Technology': r'CTL\s*3R',
    'UDP TN Hauling': r'UDP\s*TN\s*HAULING',
    'Filco': r'\bFILCO\b',
    'Heiberg Garbage': r'H?HEIBERG',
    'Black Earth Compost': r'BLACK\s*EARTH\s*COMPOST',
    'Uribe Refuse': r'URIBE\s*REFUSE',
    'Iron City Express': r'IRON\s*CITY\s*(EXPRESS)?',
    'BP Trucking': r'BP\s*TRUCKING',
    'City of Boise': r'CITY\s*OF\s*BOISE',
    'City of Deerfield Beach': r'CITY\s*OF\s*DEERFIELD',
    'City of Pembroke Pines': r'CITY\s*OF\s*PEMBROKE',
    'City of Fargo': r'CITY\s*OF\s*FARGO',
    'City of Blackfoot': r'CITY\s*OF\s*BLACKFOOT',
    'City of Dickinson': r'DICKINSON\s*CITY\s*OF',
    'Roosevelt UT': r'ROOSEVELT,?\s*UT',
    'L&L Site Services': r'L\s*&\s*L\s*SITE\s*SERVICES',
    'Bliss Environmental': r'BLISS\s*ENVIRONMENTAL',
    'A&W Iron Metal': r'A\s*&\s*W\s*IRON',
    'Midwest Sanitation': r'MIDWEST\s*SANITATION',
    'Prestige Disposal': r'PRESTIGE\s*DISPOSAL',
    'Kings Roll-Off': r'KINGS\s*ROLL.?OFF',
    'Olympic Compactor Rentals': r'OLYMPIC\s*COMPACTOR',
    'Toro Waste': r'TORO\s*WASTE',
    'Miedema Sanitation': r'MIEDEMA\s*SANITATION',
    'Greif': r'\bGREIF\b',
    'Mike Spano & Sons': r'MIKE\s*SPANO',
    'Tri-State Disposal': r'TRI.?STATE\s*(DISPOSAL)?\s*13903',
    'Enevo': r'\bENEVO\b',
    'Bi-County Disposal': r'BI.?COUNTY\s*DISPOSAL',
    'Chesapeake Waste': r'CHESAPEAKE\s*WASTE',
    'CWRR': r'\bCWRR\b',
    'City of Meridian': r'CITY\s*OF\s*MERIDIAN|MERIDIAN\s*CITY\s*OF',
    '121 Co Disposal': r'121\s*\|\s*CO\s*\|\s*DISPOSAL',
    'WM Invoice': r'INVOICE\s*\|\s*WM',
    
    # === BATCH 4 - FROM EXCEPTIONS ===
    'Arg Services': r'ARG\s*SERVICES',
    'Hill Country Waste': r'HILL\s*COUNTRY\s*WASTE',
    'Lake Disposal Service': r'LAKE\s*DISPOSAL\s*SERVICE',
    'Trash Rangers': r'TRASH\s*RANGERS',
    'Grand Rapids Iron': r'GRAND.*RAPIDS.*IRON\s*&',
    'The Trash Guys': r'THE\s*TRASH\s*GUYS',
    'AWS': r'\bAWS\b\s*(DEPT|ACADIANA)?',
    'Pacific Disposal': r'PACIFIC\s*DISPOSAL',
    'Valley Waste Service': r'VALLEY\s*WASTE\s*SERVICE',
    "Adam's Disposal": r"ADAM\'?S\s*DISPOSAL",
    'Total Reclaim': r'TOTAL\s*RECLAIM',
    'K-Town Disposal': r'K-?TOWN\s*DISPOSAL',
    'Smoky Mountain Waste': r'SMOKY\s*MOUNTAIN\s*WASTE',
    'City of Bardstown': r'BARDSTOWN',
    'Salt River Pima': r'SALT\s*RIVER\s*PIMA',
    'Boston Baler': r'BOSTON\s*BALER',
    'BNB Disposal': r'BNB\s*DISPOSAL',
    'Lake Area Disposal': r'LAKE\s*AREA\s*DISPOSAL',
    'Lance Refuse': r'LANCE\s*REFUSE',
    "Charlie's Waste": r"CHARLIE\'?S\s*WASTE",
    'Miamitown Auto Parts': r'MIAMITOWN\s*AUTO',
    'Junk Removed Now': r'JUNK\s*REMOVED\s*NOW',
    'CSD Disposal': r'\bCSD\b\s*(DISPOSAL)?',
    'Napa Recycling': r'NAPA\s*RECYCLING|\bNRW\b',
    'Akat Scrap Metal': r'AKAT\s*SCRAP',
    "Art's Garbage": r"ART\'?S\s*GARBAGE",
    'City of Sherman': r'CITY\s*OF\s*SHERMAN',
    'Sage Disposal': r'SAGE\s*DISPOSAL',
    'The Shred Truck': r'SHRED\s*TRUCK',
    'Choice Waste Services': r'CHOICE\s*WASTE\s*SERVICES',
    'Diamond Disposal': r'DIAMOND\s*DISPOSAL',
    'Cedar Grove': r'CEDAR\s*GROVE\s*(ORGANICS)?',
    'City of Hickory': r'CITY\s*OF\s*HICKORY',
    'City of Tulsa': r'CITY\s*OF\s*TULSA',
    'Cleeton Sanitation': r'CLEETON\s*SANITATION',

    # === BATCH 5 - USER REVIEW ===
    'Texas Pride Disposal': r'TEXAS\s*PRIDE\s*DISPOSAL',
    'Advance Machine & Hydraulic': r'ADVANCE\s*MACHINE',
    'Specialty Pallet': r'SPECIALTY\s*PALLET',
    'CRP Sanitation': r'CRP\s*SANITATION',
    'Texas Dumpsters': r'TEXAS\s*DUMPSTERS',
    'Honolulu Disposal': r'HONOLULU\s*DISPOSAL',
    'AJ Waste Systems': r'AJ\s*WASTE',
    'A&I Pallets': r'A\s*&\s*I\s*PALLET',
    'Ridgerunner Container': r'RIDGERUNNER',
    'Junk Solutions': r'JUNK\s*SOLUTIONS',
    'Hometown Sanitation': r'HOMETOWN.*SANITATION|HOMETOWN\s*WASTE',
    'Iron Mountain': r'IRON\s*MOUNTAIN',
    'Maverick Waste': r'MAVERICK\s*WASTE',
    'Franklin Disposal': r'FRANKLIN\s*DISPOSAL',
    'All Star Roll-Off': r'ALL\s*STAR\s*ROLL',
    'WasteVision': r'WASTEVISION',
    'City of Conyers': r'CITY\s*OF\s*CONYERS',
    
    # === BATCH 6 - HIGH PRIORITY FROM DEC 2024 ANALYSIS ===
    'AT Disposal': r'AT\s*DISPOSAL',
    'Suburban Disposal': r'SUBURBAN\s*DISPOSAL',
    'AG Logistics': r'AG\s*LOGISTICS',
    'Blue Bay Dumpsters': r'BLUE\s*BAY\s*(DUMPSTERS?|RECYCLING)',
    'Kohlmorgan Hauling': r'KOHLMORGAN',
    'DC Waste': r'DC\s*WASTE|D\.?C\.?\s*WASTE',
    'Dedicated Dumpster Service': r'DEDICATED\s*DUMPSTER|DDS\s*(INVOICE)?',
    'A1 Porta Potty': r'A-?1\s*PORTA\s*POTTY',
    'Total Disposal Inc': r'TOTAL\s*DISPOSAL\s*INC',
    'A-1 Little John': r'A-?1\s*LITTLE\s*JOHN',
    'AB-8 Waste Solutions': r'AB-?8\s*WASTE',
    'Paso Robles Waste': r'PASO\s*ROBLES\s*WASTE',
    'Bozzuto BRS Services': r'BOZZUTO|BRS\s*SERVICES',
    'Gear For Waste': r'GEAR\s*FOR\s*WASTE',
    'Stewart Sanitation': r'STEWART\s*SANITATION',
    'South San Francisco Scavenger': r'SOUTH\s*SAN\s*FRANCISCO\s*SCAVENGER',
    'Weidle Sanitation': r'WEIDLE\s*(SANITATION)?',
    'Tygarts Valley Sanitation': r'TYGARTS\s*VALLEY',
    'Georgetown Paper Stock': r'GEORGETOWN\s*PAPER\s*STOCK',
    'Nisswa Sanitation': r'NISSWA\s*SANITATION',
    'Niese Hauling': r'NIESE\s*HAULING',
    'Douglas Disposal': r'DOUGLAS\s*DISPOSAL',
    'Rockwood Sustainable Solutions': r'ROCKWOOD\s*SUSTAINABLE',
    'My Green Michigan': r'MY\s*GREEN\s*MICHIGAN',
    'Miller and Sons Disposal': r'MILLER\s*(AND|&)\s*SONS\s*DISPOSAL',
    'Ace Equipment Company': r'ACE\s*EQUIPMENT\s*COMPANY',
    "Bud's Clean Up Service": r"BUD\'?S\s*CLEAN\s*UP",
    'Brothers Disposal': r'BROTHERS\s*DISPOSAL',
    'NK Waste': r'NK\s*WASTE',
    'All States Services': r'ALL\s*STATES\s*SERVICES',
    'North Country Disposal': r'NORTH\s*COUNTRY\s*(DISPOSAL|SEPTIC)',
    'Golden Valley Disposal': r'GOLDEN\s*VALLEY\s*DISPOSAL',
    'Local Waste Solution': r'LOCAL\s*WASTE\s*SOLUTION',
    'New Prague Sanitary': r'NEW\s*PRAGUE\s*SANIT',
    'Lexington Site Services': r'LEX(INGTON)?S?\s*SITE\s*SERVICES',
    'Rhino Waste': r'RHINO\s*(WASTE|RECYCLING)',
    'Horn Sanitation': r'HORN\s*SANITATION',
    'Troupe Waste': r'TROUPE.*(WASTE|RECYCLING)',
    'Alpha Waste Disposal': r'ALPHA\s*WASTE\s*DISPOSAL',
    'DuMontelle Waste': r'DUMONTELLE\s*WASTE',
    'Humboldt County Landfill': r'HUMBOLDT\s*COUNTY\s*(LANDFILL)?',
    'Mavilyn Industries': r'MAVILYN',
    'Countryside Disposal': r'COUNTRYSIDE\s*DISPOSAL',
    'B&L Disposal': r'B\s*&\s*L\s*DISPOSAL',
    'Step Up Disposals': r'STEP\s*UP\s*DISPOSALS?',
    'Metech Recycling': r'METECH\s*(RECYCLING)?',
    'Ely Disposal Service': r'ELY\s*DISPOSAL',
    
    # === BATCH 7 - MEDIUM PRIORITY ===
    "Shular's Trash Service": r"SHULAR\'?S\s*TRASH",
    'Ideal Trash and Recycling': r'IDEAL\s*TRASH',
    'Edward Arnold Scrap Processors': r'EDWARD\s*ARNOLD',
    'J&R Sanitation': r'J\s*&\s*R\s*SANITATION',
    'Nowrush Recycling': r'NOWRUSH\s*(RECYCLING)?',
    'AMG Resources': r'AMG\s*RESOURCES',
    'California Waste Recovery': r'CALIFORNIA\s*WASTE\s*RECOVERY',
    'NW Dumpsters': r'NW\s*DUMPSTERS',
    'Palm Springs Disposal': r'PALM\s*SPRINGS\s*DISPOSAL',
    "Thompson's Sanitary Service": r"THOMPSON\'?S\s*SANITARY",
    'Waste Masters': r'WASTE\s*MASTERS',
    'Long Beach Container': r'LONG\s*BEACH\s*CONTAINER',
    'Ogborne Hauling': r'OGBORNE\s*HAULING',
    'Happen Ventures': r'HAPPEN\s*VENTURES',
    'Solid Rock Waste': r'SOLID\s*ROCK\s*WASTE',
    'Chris Rizzo Trucking': r'CHRIS\s*RIZZO\s*TRUCKING',
    'Document Destruction of Virginia': r'DOCUMENT\s*DESTRUCTION.*VIRGINIA',
    'Top of the Line Dumpsters': r'TOP\s*OF\s*THE\s*LINE\s*DUMPSTERS?',
    'Metalico Youngstown': r'METALICO\s*(YOUNGSTOWN)?',
    'Wemiga Waste': r'WEMIGA\s*WASTE',
    
    # === MUNICIPAL VENDORS ===
    'City of Snellville': r'CITY\s*OF\s*SNELLVILLE',
    'City of Sallisaw': r'CITY\s*OF\s*SALLISAW',
    'City of Richardson': r'CITY\s*OF\s*RICHARDSON',
    'City of Oakland Park': r'(CITY\s*OF\s*)?OAKLAND\s*PARK',
    'City of Lamar': r'CITY\s*OF\s*LAMAR',
    'Shawnee County Solid Waste': r'SHAWNEE\s*COUNTY\s*SOLID\s*WASTE',
    'Anchorage Solid Waste': r'SOLID\s*WASTE\s*SERVICES.*ANCHORAGE',
    'City of Sulphur Springs': r'SULPHUR\s*SPRINGS',
    'City of Great Falls': r'CITY\s*OF\s*GREAT\s*FALLS',
    'City of Quincy': r'CITY\s*OF\s*QUINCY',
    'City of Sevierville': r'CITY\s*OF\s*SEVIERVILLE',
    'City of Scottsbluff': r'CITY\s*OF\s*SCOTTSBLUFF',
    'City of Culver City': r'CITY\s*OF\s*CULVER\s*CITY',
    'City of Mesa': r'MESA\s*AZ.*UTILITIES',
    'City of Cartersville': r'CITY\s*OF\s*CARTERSVILLE',
    'City of Devils Lake': r'CITY\s*OF\s*DEVILS\s*LAKE',
    'City of Somerset': r'CITY\s*OF\s*SOMERSET',
    'City of Durant': r'CITY\s*OF\s*DURANT',
    'City of Colby': r'CITY\s*OF\s*COLBY',
    'City of Socorro': r'CITY\s*OF\s*SOCORRO',
    'City of Laramie': r'CITY\s*OF\s*LARAMIE',
    'City of Sidney': r'CITY\s*OF\s*SIDNEY',
    'City of Redwood': r'REDWOOD\s*CITY\s*(CALIFORNIA)?',
    'City of Vinita': r'CITY\s*OF\s*VINITA',
    'City of Loganville': r'CITY\s*OF\s*LOGANVILLE',
    'City of Del Rio': r'CITY\s*OF\s*DEL\s*RIO',
    'Town of Lusk': r'TOWN\s*OF\s*LUSK',
    
    # === BATCH 8 - LOWER PRIORITY ===
    'Edge Waste': r'EDGE\s*WASTE',
    'Earthwise Waste Solutions': r'EARTHWISE\s*WASTE',
    'Myers Container Service': r'MYERS\s*CONTAINER',
    'Timmons Waste Service': r'TIMMONS\s*WASTE|TWS.*WASTE',
    "Marick's Waste Disposal": r"MARICK\'?S\s*WASTE",
    'Moler Sanitation': r'MOLER\s*SANITATION',
    "Martin's Trash Service": r"MARTIN\'?S\s*TRASH",
    'Blue Moon': r'BLUE\s*MOON',
    'Olson Sanitation': r'OLSON\s*SANITATION',
    'Trinity Disposal': r'TRINITY\s*DISPOSAL',
    'MDS Waste': r'MDS\s*WASTE',
    'Total Recycling Tampa': r'TOTAL\s*RECYCLING.*WASTE',
    'U & I Sanitation': r'U\s*&\s*I\s*SANITATION',
    'Tovar Equipment': r'TOVAR\s*EQUIPMENT',
    'Prolex Compacting': r'PROLEX\s*(COMPACTING)?',
    'Break It Down': r'BREAK\s*IT\s*DOWN',
    "Dodd's Trash Hauling": r"DODD\'?S\s*TRASH",
    'Dirty Boyz Sanitation': r'DIRTY\s*BOYZ',
    'Desert Green Disposal': r'DESERT\s*GREEN\s*DISPOSAL',
    'Delta Disposal': r'DELTA\s*DISPOSAL',
    'Deep South Sanitation': r'DEEP\s*SOUTH\s*SANITATION',
    "Dayne's Waste Disposal": r"DAYNE\'?S\s*WASTE",
    'Big River Disposal': r'BIG\s*RIVER\s*DISPOSAL',
    "Clark's Disposal": r"CLARK\'?S\s*DISPOSAL",
    'Coles County Sanitation': r'COLES\s*COUNTY\s*SANITATION',
    'Roadrunner Sanitation': r'ROADRUNNER\s*SANITATION',
    'Revolution Recycling': r'REVOLUTION\s*RECYCLING',
    'Florida Waste Solutions': r'FLORIDA\s*WASTE\s*SOLUTIONS',
    "Gil's Sanitation": r"GIL\'?S\s*SANITATION",
    'Golden Environmental': r'GOLDEN\s*ENVIRONMENTAL',
    'Emterra Environmental': r'EMTERRA\s*(ENVIRONMENTAL)?',
    'McCullough Rubbish': r'MCCULLOUGH\s*RUBBISH',
    'Basin Haulage': r'BASIN\s*HAULAGE',
    'Hamilton Recycling Disposal': r'HAMILTON\s*RECYCLING.*DISPOSAL',
    'Harper Sanitation': r'HARPER\s*SANITATION',
    "Ava's Waste Removal": r"AVA\'?S\s*WASTE",
    "Howie's Trash Service": r"HOWIE\'?S\s*TRASH",
    'Hudgins Disposal': r'HUDGINS\s*DISPOSAL',
    'Gresham Sanitary Service': r'GRESHAM\s*SANITARY',
    'Pratt Sanitation': r'PRATT\s*SANITATION',
    'Capital Area Refuse': r'CAPITAL\s*AREA\s*REFUSE',
    'Empire Disposal': r'EMPIRE\s*DISPOSAL',
    'SSW-Box Services': r'SSW.?BOX\s*SERVICES',
    'Tri-State Carting': r'TRI.?STATE\s*CARTING',
    'Upper Valley Disposal': r'UPPER.*VALLEY\s*DISPOSAL',
    'Washler Garbage': r'WASHLER\s*GARBAGE',
    'Oregon City Garbage': r'OREGON\s*CITY\s*GARBAGE',
    'Gibson Truck Service': r'GIBSON\s*TRUCK\s*SERVICE',
    'Larry D Marshall Disposal': r'LARRY\s*D\.?\s*MARSHALL',
    'Norris Sanitation': r'NORRIS\s*C?\s*SANITATION',
    'Davis Disposal': r'DAVIS\s*DISPOSAL',
    'Brookings Dumpster Service': r'BROOKINGS\s*DUMPSTER',
    'Nisly Brothers': r'NISLY\s*BROTHERS',
    'Mulberry Ventures': r'MULBERRY\s*VENTURES',
    'Mauldin Trash': r'MAULDIN\s*TRASH',
    'Roberts Enterprises': r'ROBERTS\s*ENTERPRISES',
    'D&S Portable Toilets': r'D\s*&\s*S\s*PORTABLE',
    'A&C Waste Collection': r'A\s*&\s*C\s*WASTE',
    'A&L Compaction': r'A\s*&\s*L\s*COMPACTION',
    "Tim's Trash Service": r"TIM\'?S\s*TRASH",
    'Civicorps Recycling': r'CIVICORPS\s*(RECYCLING)?',
    'Full Circle Recycling': r'FULL\s*CIRCLE\s*RECYCLING',
    'NVA Services': r'\bNVA\b.*SERVICES',
    'All Florida Scrap Metals': r'ALL\s*FLORIDA\s*SCRAP',
    'Generated Materials Recovery': r'GENERATED\s*MATERIALS|GMR.*RECYCLING',
    'Ace Sanitation Service': r'ACE\s*SANITATION\s*SERVICE',
    'Enviromax Recycling': r'ENVIROMAX\s*(RECYCL)?',
    
    # === BATCH 9 - ADDITIONAL FROM REMAINING OTHER ===
    'Southwest Sanitation': r'SOUTHWEST\s*SANITATION',
    'Pennohio': r'PENNOHIO',
    'Recology': r'RECOLOGY',
    # Salandro MOVED to top of file (WM misdetection fix - pattern also fixed)
    'Young Refuse': r'YOUNG\s*REFUSE',
    'EZ Disposal': r'EZ\s*DISPOSAL',
    'BCDA The Trash Company': r'BCDA|THE\s*TRASH\s*COMPANY',
    'Mt Diablo Resource Recovery': r'MT\.?\s*DIABLO',
    'Sunny Trash Hauling': r'SUNNY\s*TRASH',
    'P&S Trucking': r'P\s*&\s*S\s*TRUCKING',
    'J&J Sanitation': r'J\s*&\s*J\s*SANITATION',
    'Real Waste Solutions': r'REAL\s*WASTE\s*SOLUTIONS',
    "Ferrell's Disposal": r'FERRELL',
    'City of Henagar': r'HENAGAR',
    'Hart Sanitation': r'HART\s*SANITATION',
    'Cowboy Sanitation': r'COWBOY\s*SANITATION',
    'Walters Sanitary Service': r'WALTERS\s*SANITARY',
    'Far West Recycling': r'FAR\s*WEST\s*RECYCLING',
    'Modern Disposal': r'MODERN\s*DISPOSAL',
    'Hepaco': r'HEPACO',
    # Greenbrier Valley MOVED to top of file (WM misdetection fix)
    'Coastal Environmental Service': r'COASTAL\s*ENVIRONMENTAL',
    'Jettison Environmental': r'JETTISON',
    'Kern County Public Works': r'KERN\s*COUNTY',
    'BestTrash': r'BESTTRASH',
    'Cards Recycling': r'CARDS\s*RECYCLING',
    'MCUD Manatee': r'MCUD|MANATEE.*UTILITIES',
    'Dyersburg Gas & Water': r'DYERSBURG',
    'City of Fort Smith': r'FORT\s*SMITH',
    'Town of Dutch John': r'DUTCH\s*JOHN',
    'William Sullivan': r'WILLIAM.*SULLIVAN',
    'Town of Greeneville': r'TOWN\s*OF\s*GREENEVI',

    # === BATCH 10 - V6 ADDITIONS (Dec 2024) ===
    # High frequency (10+ invoices)
    'SSW Frontload': r'SSW[\s\-]*(FRONTLOAD|BOX)',
    'TEG Lease': r'\bTEG\b',
    'AAA Disposal Service': r'AAA\s*(DISPOSAL|RUBBISH)',
    'Indiana Waste': r'INDIANAWASTE',
    'Marborg': r'MARBORG',
    'Lusk Disposal': r'LUSK\s*(DISPOSAL)?',
    'Butler Disposal Systems': r'BUTLER\s*DISPOSAL',
    'Waste Harmonics': r'WASTE\s*HARMONICS',
    'Marpan Supply': r'MARPAN',
    'Star Waste': r'STAR\s*WASTE',
    'Eco Sanitation': r'ECO\s*SANITATION',
    'Apple Valley Waste': r'APPLE\s*VALLEY\s*WASTE',
    'McGree Trucking': r'MCGREE\s*TRUCKING',
    'NS Disposal': r'N\.?S\.?\s*DISPOSAL',
    'Hotchkiss Disposal': r'HOTCHKISS\s*DISPOSAL',
    'LaVeine Sanitation': r'LAVEINE\s*SANITATION',
    'Tropical Trash': r'TROPICAL\s*TRASH',
    'City of Bakersfield': r'CITY\s*OF\s*BAKERSFIELD',
    'Cumberland Services': r'CUMBERLAND\s*SERVICES',
    'Bulldog Disposal': r'BULLDOG\s*DISPOSAL',
    'Wasteless Solutions': r'WASTELESS\s*SOLUTIONS',
    'Fayette Waste': r'FAYETTE\s*WASTE',
    'BKI Recycling': r'BKI\s*RECYCLING',
    'Pullman Disposal': r'PULLMAN\s*DISPOSAL',
    'Waterman Recycling': r'WATERMAN\s*RECYCLING',
    'Lemhi Sanitation': r'LEMHI\s*SANITATION',
    'Madison Materials': r'MADISON\s*MATERIALS',
    'Bloom Waste': r'BLOOM\s*WASTE',
    'Royal Oak Recycling': r'ROYAL\s*OAK\s*RECYCLING',
    'Sutton Disposal': r'SUTTON\s*DISPOSAL',
    'Control Waste': r'CONTROL\s*WASTE',
    'South Tahoe Refuse': r'SOUTH\s*TAHOE\s*REFUSE',
    'Valley Sanitation LLC': r'VALLEY\s*SANITATION',
    'Tahoe Basin Container': r'TAHOE\s*BASIN',
    'Dillon Disposal': r'DILLON\s*DISPOSAL',
    'Breezy Hollow': r'BREEZY\s*HOLLOW',
    'Canusa Hershman': r'CANUSA\s*HERSHMAN',
    'City of Tullahoma': r'CITY\s*OF\s*TULLAHOMA',
    'Styro Recycle': r'STYRO\s*RECYCLE',
    'Miles City Sanitation': r'MILES\s*CITY\s*SANITATION',
    'Klumm Brothers': r'KLUMM\s*BROTHERS',
    'P&M Reis Trucking': r'P\s*&\s*M\s*REIS',
    'City of Temple TX': r'CITY\s*OF\s*TEMPLE',
    'LCI Services': r'LCI\s*SERVICES',
    'City of Athens GA': r'CITY\s*OF\s*ATHENS',
    'Midwest Disposal IL': r'MIDWEST\s*DISPOSAL',
    # Medium frequency (5-9 invoices)
    'Seagraves Plumbing': r'SEAGRAVES\s*PLUMBING',
    'TDS LLC': r'TDS,?\s*LLC',
    'Denali Disposal': r'DENALI',
    'City of Visalia': r'CITY\s*OF\s*VISALIA',
    'City of Grand Junction': r'CITY\s*OF\s*GRAND\s*JUNCTION',
    'American Eagle Waste': r'AMERICAN\s*EAGLE\s*WASTE',
    'City of McDonough': r'CITY\s*OF\s*MCDONOUGH',
    'Rubatino Refuse': r'RUBATINO\s*REFUSE',
    'City of Douglasville': r'CITY\s*OF\s*DOUGLASVILLE',
    'BTS Inc': r'BTS\s*INC',
    'Pacific Sanitation Co': r'PACIFIC\s*SANITATION',
    'Cressman Sanitation': r'CRESSMAN\s*SANITATION',
    'Town of Gardnerville': r'GARDNERVILLE',
    'City of Tracy': r'CITY\s*OF\s*TRACY',
    'Wisneski Westmoreland': r'WISNESKI',
    'Elecke': r'ELECKE',
    'DC Metals': r'DC\s*METALS',
    'J&Jay Services': r'J\s*&\s*JAY\s*SERVICES',
    'Thomas Trash': r'THOMAS\s*TRASH',
    'C&S Disposal': r'C\s*&\s*S\s*DISPOSAL',
    'City of Fayette': r'CITY\s*OF\s*FAYETTE',
    'A&J Trash': r'A\s*&\s*J\s*TRASH',
    'Econo Waste': r'ECONO\s*WASTE',
    'Pike County Solid Waste': r'PIKE\s*COUNTY\s*SOLID',
    'Watertown Iron': r'WATERTOWN\s*IRON',
    'Kamps Pallets': r'KAMPS',
    'Jackson County Solid Waste': r'JACKSON\s*COUNTY\s*SOLID',
    'Anaconda Disposal': r'ANACONDA\s*DISPOSAL',
    'Hopper Disposal': r'HOPPER\s*DISPOSAL',
    'Allen Disposal': r'ALLEN\s*DISPOSAL',
    'Long Prairie Sanitation': r'LONG\s*PRAIRIE\s*SANITATION',
    'Becker Complete': r'BECKER\s*COMPLETE',
    'Snake River Rubbish': r'SNAKE\s*RIVER\s*RUBBISH',
    'Vanderpoel Disposal': r'VANDERPOEL',
    # Low frequency (3-4 invoices)
    'Checksammy': r'CHECKSAMMY',
    'Madden Sanitation': r'MADDEN\s*SANITATION',
    'East Central Kansas': r'EAST\s*CENTRAL\s*KANSAS',
    'SRG Spartanburg': r'SRG\s*SPARTANBURG',
    'Food To Power': r'FOOD\s*TO\s*POWER',
    'Chum Refuse': r'CHUM\s*REFUSE',
    'Southern Disposal AR': r'SOUTHERN\s*DISPOSAL.*MENA',
    'Roseburg Disposal': r'ROSEBURG\s*DISPOSAL',
    'Centre Water Works': r'CENTRE\s*WATER\s*WORKS',
    'D&S Waste': r'D\s*&\s*S\s*WASTE\s*REMOVAL',
    'Brew Crew Environmental': r'BREW\s*CREW',
    'Redfish Recycling': r'REDFISH\s*RECYCLING',
    'Kept Companies': r'KEPT\s*COMPANIES',
    'EWE Equipment': r'EWE\s*EQUIPMENT',
    'Johns Disposal WI': r'JOHNS\s*DISPOSAL',
    'H-Town Hauling': r'HTOWNHAULING|H-?TOWN\s*HAULING',
    'T-Mac Inc': r'T-?MAC,?\s*INC',
    'Golden Eagle Services': r'GOLDEN\s*EAGLE',
    # Additional Municipal
    'City of Mont Belvieu': r'MONT\s*BELVIEU',
    'City of Craig': r'CITY\s*OF\s*CRAIG',
    'City of Madisonville': r'MADISONVILLE',
    'City of Winters': r'WINTERS',
    # Additional Small Haulers  
    # Porter Trash MOVED to top of file (WM misdetection fix)
    'North Lincoln Sanitary': r'NORTH\s*LINCOLN\s*SANITARY',
    'Mountain Disposal Inc': r'MOUNTAIN\s*DISPOSAL,?\s*INC',
    'TNR Hauling': r'TNR\s*HAULING',
    'Reliable Paper': r'RELIABLE\s*PAPER',
    'Missoula Compost': r'MISSOULA\s*COMPOST',
    'Keys Sanitary': r'KEYS\s*SANITARY',
    'Standing Rock Sanitation': r'STANDING\s*ROCK\s*SANITATION',
    'Mackenzie Disposal': r'MACKENZIE\s*DISPOSAL',
    'Friends Garbage': r'FRIENDS\s*GARBAGE',
    'Coos Bay Sanitary': r'COOS\s*BAY\s*SANITARY',
    'JDog Junk Removal': r'JDOG',
    'J&T Environmental': r'J\s*&\s*T\s*ENVIRONMENTAL',
    
    # ============================================================
    # === BATCH 11 ADDITIONS (December 2024) ===
    # From vendor_review_interface.xlsx analysis - 127 new vendors
    # ============================================================
    
    # High-volume new vendors (10+ invoices)
    'TRASHCO': r'TRASHCO',
    'Waste Resources Gardena': r'WASTE\s*RESOURCES.*GARDENA',
    'City of Mount Vernon WA': r'CITY\s*OF.*MOUNT\s*VERNON',
    'HMP Inc': r'HMP,?\s*INC|BUSINESS\s*SERVICES\s*HAWAII',
    'Franklin Pallet': r'FRANKLIN\s*PALLET',
    'Empire Recycling Corporation': r'EMPIRE\s*RECYCLING\s*CORP',
    'Disposal Services LLC': r'DISPOSAL\s*SERVICES\s*LLC',
    'Lex Serv': r'LEXS\s*STE\s*SERVICES|LEXSERV',
    'Allstate Equipment Services': r'ALLSTATE\s*EQUIPMENT',
    'Apex Recycling & Disposal': r'APEX.*RECYCLING\s*&?\s*DISPOSAL',
    'American Metal & Paper': r'AMERICAN\s*METAL\s*&?\s*PAPER',
    'Efficient Roll-Off & Recycling': r'EFFICIENT\s*ROLL.?OFF',
    'Quincy Recycling': r'QUINCY\s*RECYC',
    'Amber Disposal': r'AMBER.?S?\s*DISPOSAL',
    'Pete and Pete': r'PETE\s*(&|AND)?\s*PETE|PETEANDPETE',
    'Maui Disposal Co': r'MAUI\s*DISPOSAL',
    'City of Rolla': r'CITY\s*OF\s*ROLLA',
    'United Rentals': r'UNITED\s*RENTALS',
    'City of St Anthony': r'CITY\s*OF\s*ST\.?\s*ANTHONY',
    'Texas Commercial Waste': r'TEXAS\s*COMMERCIAL\s*WASTE',
    'Sunshine Disposal & Recycling': r'SUNSHINE\s*DISPOSAL\s*&?\s*RECYC',
    'Hale County Public Works': r'HALE\s*COUNTY\s*PUBLIC\s*WORKS',
    'Marck Recycling and Waste': r'MARCK.*RECYCLING\s*&?\s*WASTE',
    'E.J. Harrison & Sons': r'E\.?J\.?\s*HARRISON',
    
    # Medium-volume new vendors (6-9 invoices)
    'HBS Denver': r'HBS.*PO\s*BOX\s*4147|HBS.*ENGLEWOOD',
    'Olathe Kansas': r'OLATHE.*KANSAS',
    'Snake River Dispose-All': r'SNAKE\s*RIVER\s*DISPOSE',
    'Town of Apple Valley': r'TOWN\s*OF\s*APPLE\s*VALLEY',
    'Federal Recycling & Waste Solutions': r'FEDERAL\s*RECYCLING\s*&?\s*WASTE',
    'Cheyenne Board of Public Utilities': r'CHEYENNE\s*BO(ARD|PU)',
    'Waste Eliminator': r'WASTE\s*ELIMINATOR',
    'Scraps Compost': r'SCRAPS.*COMPOST|ROOTED\s*IN\s*SCRAPS',
    'Waste Services Manchester': r'WASTE\s*SERVICES.*MANCHESTER|WASTESERVICES4U',
    'Delta Garbage Service': r'DELTA\s*GARBAGE\s*SERVICE',
    'All State Waste Inc': r'ALL\s*STATE\s*WASTE\s*INC',
    "Weaver's Sanitation": r"WEAVER\'?S\s*SANITATION",
    'Russell County Sanitation': r'RUSSELL\s*COUNTY\s*SANITATION|RUSSELL\s*COUNTY\s*UTILITIES',
    'Solomon Container Service': r'SOLOMON\s*CONTAINER',
    'Shamrock Waste': r'SHAMROCK\s*WASTE',
    'Olcese Waste Services': r'OLCESE\s*WASTE',
    "Abe's Trash Service": r"ABE\'?S\s*TRASH",
    'Seadrunar Recycling': r'SEADRUNAR',
    'Lakeland Disposal WI': r'LAKELAND\s*DISPOSAL.*WOODRUFF',
    'Wampler Services': r'WAMPLER\s*SERVICES',
    'Bozeman MT Utilities': r'121\s*NORTH\s*ROUSE.*BOZEMAN|BOZEMAN\s*MT\s*59771',
    'R&R Recycling Inc': r'R\s*&?\s*R\s*RECYCLING,?\s*INC',
    'Panola County Solid Waste': r'PANOLA\s*COUNTY\s*SOLID',
    'Potties for the Rockies': r'POTTIES\s*FOR\s*THE\s*ROCKIES|COLUMBIA\s*SANITARY',
    'Waterman Recy & Disposal': r'WATERMAN\s*RECY',
    'Kluesner Sanitation': r'KLUESNER\s*SANITATION',
    'Glendale Arizona Utilities': r'GLENDALE.*ARIZONA.*CURRENT\s*CHARGES',
    'Dugger Trash Service': r'DUGGER\s*TRASH',
    'City of Foley': r'CITY\s*OF\s*FOLEY',
    'Pendleton Sanitary Service': r'PENDLETON\s*SANITARY',
    'Serv-Wel Disposal': r'SERV.?WEL.*DISPOSAL|RENT.?A.?BIN',
    'Mountain High Disposal': r'MOUNTAIN\s*HIGH\s*DISPOSAL|MOUNTAINHIGHDISPOSAL',
    'Sanitation One': r'SANITATION\s*ONE',
    'ABS Sanitation': r'ABS\s*SANITATION',
    "Mac's Wood Products": r"MAC\'?S\s*WOOD\s*PRODUCTS",
    'CompostNow': r'COMPOSTNOW',
    "Wayn-O's Disposal Service": r"WAYN.?O\'?S\s*DISPOSAL",
    'Barbarino Disposal': r'BARBARINO|GARBARINO',
    'City of Green River': r'CITY\s*OF\s*GREEN\s*RIVER',
    'Eagle Equipment Service 1': r'EAGLE\s*EQUIPMENT\s*SERVICE\s*1',
    'Best Pick Disposal': r'BEST\s*PICK\s*DISPOSAL',
    "Wright's Environmental": r"WRIGHT\'?S\s*ENVIRONMENTAL",
    'Waste Removal & Recycling Inc': r'WASTE\s*REMOVAL\s*&?\s*RECYCLING,?\s*INC',
    'CWSI': r'CWSI|CONTROLLED\s*WASTE\s*SYSTEMS',
    'Industrial Services Lincoln': r'INDUSTRIAL\s*SERVICES,?\s*INC.*LINCOLN',
    'Sound Disposal Inc': r'SOUND\s*DISPOSAL,?\s*INC',
    'Hughes & Sons': r'HUGHES\s*&?\s*SONS',
    'Tahoe Truckee Sierra Disposal': r'TAHOE\s*TRUCKEE\s*SIERRA|TTSD',
    'Town of Limon': r'TOWN\s*OF\s*LIMON',
    'HESCO Hydraulic': r'HESCO.*HYDRAULIC|HYDRAULIC\s*EQUIPMENT\s*SERVICE',
    'Loren Fischer Disposal': r'LOREN\s*FISCHER\s*DISPOSAL',
    'Triple H Enterprises': r'TRIPLE\s*H\s*ENTERPRISES',
    'Liberty Ashes': r'LIBERTY\s*ASHES',
    'Waste Advantage': r'WASTE\s*ADVA(N)?TAGE',
    'Vasco Road Landfill': r'VASCO\s*ROAD\s*LANDFILL',
    'CDA Garbage': r"CDA\s*GARBAGE|COEUR\s*D\'?ALENE\s*GARBAGE|POST\s*FALLS\s*SANITATION",
    'PRIDE Disposal': r'P\.?R\.?I\.?D\.?E\s*DISPOSAL',
    'Bright Disposal Services': r'BRIGHT\s*DISPOSAL',
    'Cram-A-Lot': r'CRAM.?A.?LOT|J\.?V\.?\s*MANUFACTURING',
    'City of Emporia': r'CITY\s*OF\s*EMPORIA|EMPORIA\s*CITY\s*OF\s*EMPORIA',
    'Cook Maintenance': r'COOK\s*MAINTENANCE',
    'City of Gainesville TX': r'CITY\s*OF\s*GAINESVILLE.*TX',
    'Eagle Equipment Corporation': r'EAGLE\s*EQUIPMENT\s*CORP',
    "Dan's Sanitation": r"DAN\'?S\s*SANITATION",
    "Ed's Disposal": r"ED\'?S\s*DISPOSAL",
    'EarthSavers': r'EARTHSAVERS|EARTH\s*SAVERS',
    'Advanced Document Solutions': r'ADVANCED\s*DOCUMENT\s*SOLUTIONS',
    'Pyles Demolition Recycling': r'PYLES\s*DEMOLITION',
    
    # Lower-volume new vendors (5 invoices)
    'United Waste Systems': r'UNITED\s*WASTE\s*SYSTEMS',
    'Pluffmud Recycling': r'PLUFFMUD',
    'Durflinger Disposal Service': r'DURFLINGER\s*DISPOSAL',
    'Miller Waste Systems': r'MILLER\s*WASTE\s*SYSTEMS',
    'Nooksack Valley Disposal': r'NOOKSACK\s*VALLEY',
    'Anchor Technical': r'ANCHOR\s*TECHNICAL',
    'Recycling Center of North Dakota': r'RECYCLING\s*CENTER\s*OF\s*NORTH\s*DAKOTA',
    'Central Valley Disposal': r'CENTRAL\s*VALLEY\s*DISPOSAL',
    "Jim Dedman's Sanitation": r"JIM\s*DEDMAN\'?S\s*SANITATION",
    'Buldo Container & Disposal': r'BULDO',
    'Walker Garbage and Recycling': r'WALKER\s*GARBAGE\s*&?\s*RECYCLING',
    'Joseph J. Runner': r'JOSEPH\s*J\.?\s*RUNNER',
    'Kalamazoo Transfer Station': r'KALAMAZOO\s*TRANSFER',
    'Volunteer Disposal West': r'VOLUNTEER\s*DISPOSAL\s*WEST',
    'City of Winfield': r'CITY\s*OF\s*WINFIELD',
    'City of Lakeland FL': r'CITY\s*OF\s*LAKELAND|LAKELAND\s*UTILITIES',
    'Timberline LLC': r'TIMBERLINE\s*LLC',
    'Junk King': r'JUNK\s*KING',
    'J & M Sanitation': r'J\s*&?\s*M\s*SANITATION',
    'Mid-Ohio Sanitation & Recycling': r'MID.?OHIO\s*SANITATION',
    'Industrial Waste & Salvage': r'INDUSTRIAL\s*WASTE\s*&?\s*SALVAGE',
    'S.B. Cox': r'S\.?B\.?\s*COX',
    'Happy Can Disposal': r'HAPPY\s*CAN',
    'Graybill Equipment & Repair': r'GRAYBILL\s*EQUIPMENT',
    'Hillsboro Garbage Disposal': r'HILLSBORO\s*GARBAGE',
    'Gardner Disposal Service': r'GARDNER\s*DISPOSAL\s*SERVICE',
    'Sweetland': r'SWEETLAND\s*LTD',
    'Equipment Depot Northeast': r'EQUIPMENT\s*DEPOT\s*NORTHEAST',
    'CTL Washington': r'CTL\s*WASHINGTON|CTL\s*8002\s*S',
    'Reliable Paper Recycling': r'RELIABLE\s*PAPER\s*RECYC|ELIABLE\s*PAPER',
    'Sunrise Sanitation Service': r'SUNRISE\s*SANITATION\s*SERVICE',
    'Copper State Sanitation': r'COPPER\s*STATE\s*SANITATION',
    'Industrial Refuse Service': r'INDUSTRIAL\s*IRS\s*REFUSE\s*SERVICE|INDUSTRIAL\s*REFUSE\s*SERVICE',

}


def detect_vendor(text):
    """Detect vendor from invoice OCR text. Returns vendor name or 'OTHER'."""
    if not text or str(text) == 'nan':
        return 'OTHER'
    text_upper = str(text).replace(chr(92) + "n", " ").upper()
    for vendor, pattern in VENDOR_PATTERNS.items():
        if re.search(pattern, text_upper):
            return vendor
    return 'OTHER'


def get_vendor_count():
    """Return total number of vendor patterns."""
    return len(VENDOR_PATTERNS)


if __name__ == '__main__':
    print(f"Vendor detection v7: {get_vendor_count()} patterns")
    print("\nV7 Changes - WM Misdetection Fixes:")
    print("=" * 50)
    print("Added 25+ new vendor patterns before 'Waste Management':")
    print("  - West Central Sanitation (53 invoices)")
    print("  - Boro Wide (49 invoices)")
    print("  - Bruin Waste Management (41 invoices)")
    print("  - Appalachian Waste Management (18 invoices)")
    print("  - Garden State Waste Management (13 invoices)")
    print("  - Tacoma Public Utilities (11 invoices)")
    print("  - Heartland Waste Management (7 invoices)")
    print("  - And 18+ more...")
    print("\nMoved existing patterns before WM:")
    print("  - Win Waste (29 invoices)")
    print("  - Porter Trash (10 invoices)")
    print("\nFixed patterns:")
    print("  - Salandro Refuse: r'SALANDRO' (was r'SALANDR.?\\s*REFUSE')")
    print("\nTotal misdetections fixed: ~317 invoices")
